### ISSUE TITLE
Slab/Stair facades appear to be directionally locked

### ISSUE THREAD

**Issue by MuteTiefling** [Porting-Dead-Mods/Cable-Facades#23]
Unsure how feasible this is, but it'd be nice if stair facades functioned like normal stairs, connecting to adjacent stairs, etc. 

Currently they appear to always place with the back facing north.

Similarly, would be nice if slab facades could be top slabs.

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the FacadeItem class to store the full BlockState instead of just the Block for stairs and slabs. This allows us to preserve the orientation and half (top/bottom) information for these blocks.

You can review changes in this commit: https://github.com/jjyutm4532/Porting-Dead-Mods-Cable-Facades-23/commit/42a823a2ea82121fd52b8200061d3c412f8ebd56.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Leclowndu93150** [comment]
i think it is feasable. (i think)

**Comment by HeatherComputer** [comment]
👀

**Comment by HeatherComputer** [comment]
For the sake of tracking, I'll mention #27 here as it would *mostly* solve this issue. 

With this implementation however, corner stairs would *not* be doable - this is by design:

![image](https://github.com/user-attachments/assets/de8bd6c9-2d5c-4db8-866c-fbae44b97902)

**Comment by Thepigcat76** [comment]
Implemented by heather <3
