### ISSUE TITLE
Integrated Dynamics Logic Cable

### ISSUE THREAD

**Issue by DataDalton** [Porting-Dead-Mods/Cable-Facades#4]
When allowing the Integrated Dynamics Logic cable in the config it produces an xray error:

![2024-11-16_16 01 36](https://github.com/user-attachments/assets/39d88104-3f51-42a6-9fd6-962cf7f8815b)

**Comment by Thepigcat76** [comment]
Yea we encountered this one in testing as well... integrated dynamics has a bunch of abstractions for stuff in their library, hence their pipes are a bit finicky. Supermartinj is working on a pr to fix rendering of certain block faces. That might address this issue... Otherwise we will need to talk with the ID devs

**Comment by Thepigcat76** [comment]
No idea how to do this. Will close it for now. If anyone wants to implement it, please make a pr
